import { Offer, TieredOfferData } from './interfaces';
export declare class SallaTieredOffer {
    constructor();
    tieredOfferData: TieredOfferData;
    apiOfferData: Offer;
    currentTierIndex: number;
    currentTier: string;
    activeTabTier: string;
    canRender: boolean;
    isLoading: boolean;
    loyaltyProgramText: string;
    currentTierText: string;
    discountText: string;
    benefitText: string;
    componentWillLoad(): Promise<void>;
    private checkFeatureEnabled;
    private checkCartExists;
    private validateCouponCompatibility;
    private fetchTieredOfferData;
    private initializeComponent;
    componentDidLoad(): void;
    private mapApiDataToTiers;
    private findCurrentTierIndex;
    private updateOfferValues;
    private getLoadingSkeletonView;
    private getCurrentTierData;
    private getProgressWidth;
    private handleTabClick;
    private calculateMilestonePosition;
    private getMilestoneStyles;
    private getMilestoneIconStyles;
    private renderProgressBarBackground;
    private renderMilestoneIcon;
    private renderMilestoneName;
    private renderMilestones;
    private renderProgressBar;
    private renderTabs;
    render(): any;
}
